services:
  mysql:
    image: mysql:8.0
    container_name: student-job-portal-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: student_job_portal
      MYSQL_USER: portal_user
      MYSQL_PASSWORD: portal_pass
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

